name: ISSUE_TEMPLATE
description: Nova tarefa
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Descrição da tarefa.
    validations:
      required: false
  - type: dropdown
    id: scope
    attributes:
      label: Escopo
      description: Especifique o escopo da tarefa
      options:
        - Back-End
        - Front-End
        - Documentation
        - Outro
      multiple: true
    validations:
      required: true
  - type: textarea
    id: suggestions
    attributes:
      label: Sugestões
      description: |
      Algumas sugestões ou comentários adicionais para facilitar a execução da tarefa 
    validations:
      required: false
